install.packages("rvest")
install.packages("robotstxt")
install.packages("dplyr")
library(rvest)
library(robotstxt)
library(dplyr)
Path = paths_allowed("https://www.flipkart.com/mobiles/mi~brand/pr?sid=tyy,4io&otracker=nmenu_sub_Electronics_0_Mi")
link<-"https://www.flipkart.com/mobiles/mi~brand/pr?sid=tyy,4io&otracker=nmenu_sub_Electronics_0_Mi"
web<-read_html(link)
name=web%>%html_nodes(".s-line-clamp-2")%>%html_text()
View(name)
rating=web%>%html_nodes(".aok-align-bottom")%>%html_text()
View(rating)
price<-web%>%html_nodes(".a-price-whole")%>%html_text()
View(price)
discount<-web%>%html_nodes(".a-color-price")%>%html_text()
View(discount)
phones<-data.frame(name,rating,price,discount)
View(phones)
write.csv(phones,"flights data.csv")